### ISSUE TITLE
how does the second parameter gets added to the spread operator

### ISSUE THREAD

**Issue by hussamkhatib** [iamshaunjp/react-redux-complete-playlist#13]
in the below code why do we need the second parameter next to spread op('ninja'),how and what will addition be done
```
 // addNinja = (ninja) => {
   // ninja.id = Math.random();
    let ninjas = [...this.state.ninjas, ninja];
    //this.setState({
      //ninjas: ninjas
    //});
  //}
```

**Comment by davisthemenace** [comment]
thats for adding or pushing the new value in the new 'ninjas' array. Basically the first parameter will copy the existing 'ninjas' into new array and second parameter will append or push the new one in after that.

**Comment by hussamkhatib** [comment]
thank you
