### ISSUE TITLE
Why the repo is empty?

### ISSUE THREAD

**Issue by vidoluco** [iamshaunjp/react-redux-complete-playlist#20]

**Comment by usumuduurai** [comment]
It is not empty, only the master. You can select the branch by lessons as he said in the video at 3:21:
https://www.youtube.com/watch?v=OxIDLw0M-m0&list=PL4cUxeGkcC9ij8CfkAY2RAGb-tmkNwQHG&index=1

**Comment by vidoluco** [comment]
You're right, my fault. Thank you, I didn't watch that video.
